version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-banking-account
    environment:
      POSTGRES_DB: banking-account
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/banking-account
      - SONARQUBE_JDBC_USERNAME= admin
      - SONARQUBE_JDBC_PASSWORD= Password2023
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/log

volumes:
  postgresql:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: