#DATABASE
POSTGRESQL_USERNAME: root
POSTGRESQL_PASSWORD: root
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DB: banking-account

#SERVER
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

##JWT-SECRET
SECRET_KEY: 36763979244226452948404D6351665468576D5A7134743777217A25432A462D
EXPIRATION: 5686000
REFRESH_TOKEN_EXPIRATION: 60480000