#DATABASE
POSTGRESQL_USERNAME: root
POSTGRESQL_PASSWORD: admin
POSTGRESQL_HOST: 192.168.1.216
POSTGRESQL_PORT: 5432
POSTGRESQL_DB: banking-account
POSTGRESQL_DRIVER: org.postgresql.Driver


#SERVER
SERVER_PORT: 9090
ACTIVE_PROFILE: test