spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking-account
    driver-class-name: org.postgresql.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    format:
      date: yyyy-MM-dd
  application:
    security:
      jwt:
        secret-key:
        expiration:  # Temps d'expiration du jeton en millisecondes (par exemple, 1 heure)
        refresh-token:
          expiration:


  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
      verify:
        host: http://localhost:8080
      smtp:
        connectiontimeout: 10000
        timeout: 10000
        starttls:
          required: true
