spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking-account
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#sonar:
#  projectKey: banking-account
#  projectName: banking-account
#  host.url: http://localhost:9000
#  login: admin
#  password: Password2023